# Project information
site_name: opengpt
site_url: https://opengpt.jina.ai
site_author: jina-ai GmbH
site_description: >-
  Easily and cost-effectively LLM deployments on any cloud. 

# Repository
repo_url: https://github.com/jina-ai/opengpt
repo_name: jina-ai/opengpt
edit_uri: edit/master/docs/

#Copyright
copyright: © 2023 jina-ai

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/dstack-logo-notext.svg
  favicon: assets/images/dstack-fav-32.ico
  icon:
    repo: custom/github
    edit: material/pencil
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
    #    - navigation.path
    - content.code.copy
    - content.action.edit
    #    - navigation.indexes
    - navigation.tabs
    #    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    #    - navigation.expand
    - navigation.top
    - announce.dismiss
    - navigation.tracking
    - navigation.footer

# Plugins
plugins:
#  - blog:
#      blog_dir: blog
#      blog_toc: true
#  - social:
#      cards_layout_options:
#        background_color: "black"
#        color: "#FFFFFF"
#        font_family: Roboto
  - search
  - redirects:
      redirect_maps:
        'quickstart.md': 'docs/index.md'
        'docs/quick-start.md': 'docs/index.md'
        'docs/installation/index.md': 'docs/index.md'
#        'tutorials/dolly.md': 'examples/dolly.md'
#        'tutorials/stable-diffusion.md': 'examples/stable-diffusion.md'
#        'tutorials/tensorboard.md': 'examples/tensorboard.md'
#        'tutorials/wandb.md': 'examples/wandb.md'
#  - typeset

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
      permalink: true
  - attr_list
  - md_in_html
  - footnotes

# Customization
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/termynal.css
  - assets/stylesheets/landing.css
extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/termynal.js
extra:
  homepage: /
  generator: false
#  analytics:
#    provider: google
#    property: G-XXXXXX
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/jina-ai/opengpt
    - icon: /fontawesome/brands/python
      link: https://pypi.org/project/open-gpt-torch
#    - icon: /fontawesome/brands/docker
#      link: https://hub.docker.com/r/jina-ai/opengpt
#    - icon: /fontawesome/brands/slack
#      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
#    - icon: /fontawesome/brands/twitter
#      link: https://twitter.com/dstackai
  status:
    new: Recently added
# Page tree
nav:
  - Home: index.md
  - Docs:
      - Getting started:
          - Quick start: docs/index.md
#          - Installation:
#              - Docker: docs/deployment/docker.md
#              - Hugging Face Spaces: docs/deployment/hf-spaces.md
#              - Clouds: docs/deployment/clouds.md
      - Guides:
#          - Dev environments: docs/guides/dev-environments.md
#          - Tasks: docs/guides/tasks.md
#          - Artifacts: docs/guides/artifacts.md
          - Projects: docs/guides/projects.md
      - Reference:
          - CLI:
              - opengpt serve: docs/reference/cli/start.md
              - opengpt deploy: docs/reference/cli/start.md
  - Examples: https://github.com/jina-ai/opengpt/blob/main/examples
#  - Slack: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
  - Blog:
      - blog/index.md
#  - Twitter: https://twitter.com/jina-ai/
